---
title: "Course Calendar and Materials"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
---


Each week, classes will be a mix of lecture, class discussion, and short activities. 

*  **You should bring your laptop with you to every class period.** We will be using R and RStudio extensively in this course. In particular, students are encouraged to write homework assignments in R Markdown and compile to pdf for the submission.
* Assigned readings for each week are posted. Whether you learn better by reading prior to lecture, or hearing a lecture prior to reading is up to you.
* Weeks will typically alternate between homework assignments and in-class quizzes, with homework due dates and quizzes falling on Thursdays. 
    - Homework assignments should be submitted in D2L by 11pm on the due date. 
    - Each quiz will cover the content from the previous week's homework, e.g., Quiz 1 will cover content from Homework 1.


---

## Week 1 (Jan 19--21)

---

_Course Overview_

* [Lecture 1 slides](lectures/Lecture1Slides-Jan20.pdf)
* Case study: [Challenger explosion](R/Week1-Jan20-Challenger.html) ([RMD](R/Week1-Jan20-Challenger.Rmd)) ([Dalal et al., 1989](references/Dalal_etal_1989-Challenger.pdf))

---

## Week 2 (Jan 24--28)

---

### _Content_

- Probability distributions for categorical data: binomial, multinomial, negative binomial
- Asymptotic inference for one and two proportions
- Exact (binomial) inference for one proportion
- Maximum likelihood estimation
- Types of sampling and studies
- Probability structure for $I\times J$ contingency tables

### **Assigned readings**

- Chapter 1 Sections 1.1--1.3, 1.6
- Chapter 2 Section 2.1

### **Tuesday**

- [Lecture 2 notes](notes/NotesJan25.pdf)
- [Hypothesis testing playbook](handouts/Hypothesis_Testing_Playbook.pdf)
- [Inference for proportions examples](handouts/Inference_for_Proportions-Examples.html) ([Rmd](handouts/Inference_for_Proportions-Examples.Rmd))
- [Inference for proportions solutions](handouts/Inference_for_Proportions-Examples-Solns.html) ([Rmd](handouts/Inference_for_Proportions-Examples-Solns.Rmd))

### **Thursday**

- [Lecture 3 slides](lectures/Lecture3Slides-Jan27-Sec2.1-2.3.pdf)
- [Lecture 3 notes](notes/NotesJan27.pdf) 
- [MLE Example in R](R/MLE-Jan27.R)

### **Homework/Quiz**

- [Homework 1](homework/Stat439-S22-HW1.pdf) ([Rmd](homework/Stat439-S22-HW1.Rmd)) due Thur Jan 27 by 11pm --- probability distributions for categorical data, asymptotic and exact inference for one proportion, MLE
- [Agresti Chapter 1 Exercises](book/Ch1Ex.pdf)

---

## Week 3 (Jan 31--Feb 4)

---

### _Content_

- Asymptotic inference for $2\times 2$ tables: difference in proportions, relative risk, odds ratio

### **Assigned readings**

- Chapter 2 Sections 2.2--2.3

### **Tuesday**

- [Lecture 4 notes](notes/NotesFeb1.pdf)
- [Asymptotic inference for 2x2 tables in-class R code](R/Inference_2x2Tables-Feb1.R)
- [Extended asymptotic inference for 2x2 tables](handouts/Inference_2x2_Tables.pdf) ([Rmd](handouts/Inference_2x2_Tables.Rmd))

### **Thursday**

- [Lecture 5 notes](notes/NotesFeb3.pdf)
- Extra reference: Lecture slides from [Dr. Bandyopadhyay's](https://people.vcu.edu/~dbandyop/) BIOS 625 course at Virginia Commonwealth University
    * [Comparing proportions](references/4-Comparing_Proportions.pdf) (see Slide 15 for a nice explanation of why RR is not estimable in case-control studies)


### **Homework/Quiz**

- Quiz 1 in class Thur Feb 3

---

## Week 4 (Feb 7--11)

---

### _Content_

- Randomization tests for $2\times 2$ tables
- Fisher's Exact Test for $2\times 2$ tables
- Chi-squared tests of independence for $I\times J$ contingency tables
- Association in three-way tables

### **Assigned readings**

- Chapter 2 Sections 2.4, 2.6--2.7

### **Tuesday**

- [Lecture 6 notes](notes/NotesFeb8.pdf)
- [Exact inference in R](R/Week4-Feb8-Resampling.html) ([Rmd](R/Week4-Feb8-Resampling.Rmd))

### **Thursday**

- [Chi-squared tests for contingency tables slides](lectures/Lecture7Slides-Feb10-Sec2.4.pdf)
    * Dr. Greenwood's [annotated notes](notes/ind_annotated-Feb10.pdf)
- [Swedish fish example in R](R/Week4-Feb10-SwedishFishConsumption.html) ([Rmd](R/Week4-Feb10-SwedishFishConsumption.Rmd))
    * Dr. Greenwood's [annotated notes](notes/swedishfish_annotated-Feb10.pdf)
- [Association in three-way tables and Simpson's paradox slides](lectures/Lecture7Slides-Feb10-Sec2.7.pdf)
    * Dr. Greenwood's [annotated notes](notes/three-way_annotated-Feb10.pdf)
- [Berkeley graduate admissions R script](R/Week4-Feb10-BerkeleyGradAdmissions.R)

### **Homework/Quiz**

- [Homework 2](homework/Stat439-S22-HW2.pdf) ([Rmd](homework/Stat439-S22-HW2.Rmd)) due Thur Feb 10 by 11pm --- types of sampling and studies, asymptotic inference for $2\times 2$ tables, randomization tests, Fisher's Exact Test

---

## Week 5 (Feb 14--18)

---

### _Content_

- Components of a generalized linear model (GLM)
- GLMs for binary data

### **Assigned readings**

- Chapter 3 Sections 3.1--3.2
- Chapter 4 Sections 4.1--4.6
- Chapter 5 Section 5.3


### **Tuesday**

- [Confounders and effect modifiers slides](lectures/Lecture8Slides-Feb15-Sec2.7cont.pdf)
- [Lecture 8 notes](notes/NotesFeb15.pdf)

### **Thursday**

- Quiz 2 only

### **Homework/Quiz**

- Quiz 2 in class Thur Feb 17

---

## Week 6 (Feb 21--25)

---

### _Content_

- GLMs for binary data (continued)

### **Assigned readings**

- Continued from last week

### **Tuesday**

- [Framingham heart study example](R/Week6-Feb22-GLMIntro-Framingham.html) ([Rmd](R/Week6-Feb22-GLMIntro-Framingham.Rmd)) (updated after 2/24 class)
- [In-class notes](notes/NotesFeb22.pdf)

### **Thursday**

- [In-class notes](notes/NotesFeb24.pdf)

### **Homework/Quiz**

- [Homework 3](homework/Stat439-S22-HW3.pdf) ([Rmd](homework/Stat439-S22-HW3.Rmd)) due Thur Feb 24 by 11pm --- chi-squared tests of independence, three-way tables, components of a GLM

---

## Week 7 (Feb 28--Mar 4)

---

### _Content_

- Logistic regression with categorical predictors

### **Assigned readings**

- Continued from last week

### **Tuesday**

- Berkeley example R files:
    * [Ungrouped vs grouped data and model comparison tests](R/Week6-LogReg-Berkeley.R)
    * [Linear combinations of coefficients](R/Week6-LinContrasts-Berkeley.R)
- [In-class notes](notes/NotesMar1.pdf)

### **Thursday**

- [In-class notes](notes/NotesMar3.pdf)

### **Homework/Quiz**

- Quiz 3 in class Thur Mar 3


---

## Week 8 (Mar 7--11)

---

### _Content_

- GLMs for count data
- Model fitting, selection and diagnostics for GLMs

### **Assigned readings**

- Chapter 3 Sections 3.3--3.5
- Chapter 5 Sections 5.1--5.3

### **Tuesday**

- Horseshoe crabs Poisson regression example ([Rmd](R/Week8-Mar8-HorseshoeCrab.Rmd)) ([html](R/Week8-Mar8-HorseshoeCrab.html))
- [In-class notes](notes/NotesMar8.pdf)
- [R console from class](notes/RConsoleMar8.txt)


### **Thursday**

- Homicides and gun registraction Poisson regression example ([Rmd](R/Week8-Mar10-GunRegistration.Rmd)) ([html](R/Week8-Mar10-GunRegistration.html)) (updated 3/22 and 3/24)
- [In-class notes](notes/NotesMar10.pdf)


### **Homework/Quiz**

- [Homework 4](homework/Stat439-S22-HW4.pdf) ([Rmd](homework/Stat439-S22-HW4.Rmd)) due Thur Mar 10 by 11pm in Gradescope --- GLMs for binary data (logistic regression)

---

## Week 9 (Mar 21--25)

---

### _Content_

- GLMs for count data (continued)
- Model fitting, selection and diagnostics for GLMs

### **Assigned readings**

- Continued from last week

### **Tuesday**

- [In-class notes](notes/NotesMar22.pdf)
- See R example from last week for updated code


### **Thursday**

- [In-class notes](notes/NotesMar24.pdf)
- See R example from last week for updated code

### **Homework/Quiz**

- Quiz 4 in class Thur Mar 24

---

## Week 10 (Mar 28--Apr 1)

---

### _Content_

- Model fitting, selection and diagnostics for GLMs (cont)

### **Assigned readings**

- Chapter 6 Sections 6.1--6.2

### **Tuesday**

- [Model selection slides](lectures/LectureSlides-Mar22-ModelSelection.pdf)
- [Model selection with horseshoe crab data](R/Week9-Mar22-ModelSelection-Horseshoe.html) ([Rmd](R/Week9-Mar22-ModelSelection-Horseshoe.Rmd))
- [In-class notes](notes/NotesMar29.pdf)

### **Thursday**

- [STAT 439 R functions](R/Stat439-RFunctions.R)
- [Baseline logit model example: Travel data, Part 1](R/Week10-Mar29-Travel.R)
- [In-class notes](notes/NotesMar31.pdf)

### **Homework/Quiz**

- [Homework 5](homework/Stat439-S22-HW5.pdf) ([Rmd](homework/Stat439-S22-HW5.Rmd)) due Thur Mar 31 by 11pm --- GLMS for Poisson regression, model fitting, selection and diagnostics for GLMs

---

## Week 11 (Apr 4--8)

---

### _Content_

- Multicategory logit models (cont)

### **Assigned readings**

- Chapter 8 Sections 8.1, 8.3, 8.5

### **Tuesday**

- [Baseline logit model example: Travel data, Part 2](R/Week11-Apr5-Travel-cont.R)
- [In-class notes](notes/NotesApr5.pdf)


### **Thursday**

- [Cumulative logit model examples](R/Week11-Apr5-Cumulative_Logit.R)
- [In-class notes](notes/NotesApr7.pdf)

### **Homework/Quiz**

- Quiz 5 in class Thur Apr 7

### **Project Deadline**

- Data analysis proposal due by 11pm Friday Apr 8 in Gradescope.



---

## Week 12 (Apr 11--15)

---

### _Content_

- Modeling correlated data
    * Models for matched pairs
    * Marginal models (GEEs)
    * Generalized linear mixed models (GLMMs)

### **Assigned readings**

- Chapter 8 Sections 8.1--8.2 (skip 8.3--8.6)
- Chapter 9 Sections 9.1--9.2 (skip 9.3--9.5)
- Chapter 10 Sections 10.1--10.2 (skip 10.3--10.5)

### **Tuesday**

- [Correlated data slides](lectures/LectureSlides-Apr12-Correlated.pdf) (updated Apr 19)
- R Example: [Matched pairs](R/Week12-Apr12-McNemar.R)
- [In-class notes](notes/NotesApr12.pdf)

### **Thursday**

- [In-class notes](notes/NotesApr14.pdf)

### **Homework/Quiz**

- [Homework 6](homework/Stat439-S22-HW6.pdf) ([Rmd](homework/Stat439-S22-HW6.Rmd)) due Mon Apr 18 by 11pm --- baseline and cumulative logit models for multinomial data

---

## Week 13 (Apr 18--22)

---

### _Content_

- Modeling correlated data (continued)

### **Assigned readings**

- Continued from last week

### **Tuesday**

- [Epilepsy data R Example](R/Week12_Apr14_Epilepsy.pdf) ([Rmd](R/Week12_Apr14_Epilepsy.Rmd))
- See D2L Content for recording of Dr. Greenwood's lecture

### **Thursday**

- Correlated data slides and epilepsy example (continued)
- [In-class notes](notes/NotesApr21.pdf)

### **Homework/Quiz**

- Quiz 6 in class Thur Apr 21

### **Project Deadline**

- Draft report due by 11pm Friday Apr 22 in Gradescope.

---

## Week 14 (Apr 25--29)

---

### _Content_

- Modeling correlated data (continued)
- GLM leftovers:
    * Residual diagnostics
    * Dealing with missing data

### **Assigned readings**

- Continued from last week
- Some content not in textbook

### **Tuesday**

- Class cancelled

### **Thursday**

- Finish epilepsy data example
- [In-class notes](notes/NotesApr28.pdf)

Correlated binary data example:

- [Correlated binary data R Example](R/Week14-Correlated-Binary.html) ([Rmd](R/Week14-Correlated-Binary.Rmd))
- Videos:
    * [Exploratory data analysis](https://montana.techsmithrelay.com/tpCz)
    * [Generalized linear mixed model](https://montana.techsmithrelay.com/ANUY)
    * [Marginal model](https://montana.techsmithrelay.com/4nW3)
- [Video notes](notes/Binary-Correlated-Example.pdf)


### **Homework/Quiz**

- [Homework 7](homework/Stat439-S22-HW7.pdf) ([Rmd](homework/Stat439-S22-HW7.Rmd)) due Thur Apr 28 by 11pm --- population-averaged models (i.e., marginal models, GEEs), subject-specific models (i.e., generalized linear mixed effects models)

### **Project Deadline**

- Peer assessments due by 11pm Friday Apr 29 in Gradescope.

---

## Week 15 (May 2--6)

---

### _Content_

- Classification and clustering

### **Assigned readings**

- Review Chapter 4 Section 4.6
- Chapter 11 Sections 11.1--11.3

### **Tuesday**/**Thursday**

- [Week 15 slides](lectures/week15-slides.html) ([Rmd](lectures/week15-slides.Rmd))
- Choose your own adventure:
    * [Prediction](R/Week15/Prediction.html) ([Rmd](R/Week15/Prediction.Rmd))
    * [Classification](R/Week15/Classification.html) ([Rmd](R/Week15/Classification.Rmd))
    * [Clustering](R/Week15/Clustering.html) ([Rmd](R/Week15/Clustering.Rmd))
    * [Linear discriminant analysis](R/Week15/LDA.html) ([Rmd](R/Week15/LDA.Rmd))
- [Tuesday in-class notes](notes/Notes-May3.pdf)

### **Homework/Quiz**

- Quiz 7 in class Thur May 5 (make-up quiz only)

### **Project Deadline**

- Final report due by 11pm Friday May 6 in Gradescope.

---

## Final Exam Week

---

### Take-home final exam

Released Friday, May 6. Due by 11pm Wednesday, May 11 in Gradescope.

### Project presentations

Thursday, May 12 8:00--9:50am
